# numpy

In [1]:
import numpy as np

In [4]:
# create
arr = np.array([11, 22, 33])
arr

array([11, 22, 33])

In [5]:
type(arr)

numpy.ndarray

In [6]:
# 2D array
np.array([[11, 22], [33, 44]])

array([[11, 22],
       [33, 44]])

In [8]:
list(range(1, 20,3))

[1, 4, 7, 10, 13, 16, 19]

In [9]:
np.arange(1, 20, 3)

array([ 1,  4,  7, 10, 13, 16, 19])

In [10]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
# array of zeros np.zeros(shape)
np.zeros((4, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
#0.0 => 0.

In [13]:
# check the data type of an array
arr = np.zeros((4, 5))
arr.dtype

dtype('float64')

In [14]:
# linearly spaced values
# np.linspace(start,stop, no_of_values_between_start_stop)
np.linspace(0,20,4)

array([ 0.        ,  6.66666667, 13.33333333, 20.        ])

In [15]:
np.linspace(0,24,4)

array([ 0.,  8., 16., 24.])

In [16]:
# creating an array from an existing data
# numpy.asarray(data, dtype=None)
arr = np.asarray([[11, 22, 33],[44, 55, 66]],dtype=float)
arr



array([[11., 22., 33.],
       [44., 55., 66.]])

In [17]:
arr.shape  

(2, 3)

In [22]:
# dimension of an array is the length of the shape tuple.
# Restructuring a numpy array
arr = np.zeros(8)
arr.shape

(8,)

In [27]:
# converting 1D array to 2D array: but remember number of elements must 
# ..be same after conversion
arr1d = np.zeros(8)
arr_3d = arr1d.reshape((2,2,2))
print(arr_3d)
print("#"*20)
arr_2d = arr1d.reshape((2,4))
print(arr_2d)

[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]
####################
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [30]:
# converting multi dimensional array to 1D

arr_2d = np.array([[11, 22], [33, 44]])
print(arr_2d)
print("#"*10)
arr_1d = arr_2d.ravel()
print(arr_1d)

[[11 22]
 [33 44]]
##########
[11 22 33 44]


## Indexing

In [31]:
arr = np.array([11, 22, 33, 44, 55])
arr

array([11, 22, 33, 44, 55])

In [32]:
arr[0]

11

In [33]:
arr[-1]

55

In [34]:
# access multiple values together
# method 1
arr = np.array([11, 22, 33, 44, 55, 66, 77, 88])
arr[[0,3,5]]

array([11, 44, 66])

In [37]:
# method 2:, using slice object
arr = np.arange(1,50,3)
print(arr)
print("#"*10)
slice_obj = slice(1, 10, 2)  # [1, 3, 5, 7, 9]
print(arr[slice_obj])

# method 3: using slicing
print(arr[1:10:2])


[ 1  4  7 10 13 16 19 22 25 28 31 34 37 40 43 46 49]
##########
[ 4 10 16 22 28]
[ 4 10 16 22 28]


In [44]:
print(slice_obj)

slice(1, 10, 2)


In [38]:
arr[2:]

array([ 7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49])

In [39]:
arr[:12]

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34])

In [40]:
arr[1:5]

array([ 4,  7, 10, 13])

### Slicing of 2D array


In [41]:
arr = np.array([[11, 22, 33, 44], [55, 66, 77, 88], [10,20,30,40], [50,60,70,80]])
arr

array([[11, 22, 33, 44],
       [55, 66, 77, 88],
       [10, 20, 30, 40],
       [50, 60, 70, 80]])

In [42]:
# syntax: arr[row_slice_indexes, column_slice_index]
arr[0:2,1:3]

array([[22, 33],
       [66, 77]])

## numpy array attributes

In [46]:
import numpy as np
arr =np.array([[11, 22, 33, 44], [55, 66, 77, 88]])
print(arr.shape)
print(arr.ndim)  # dimension
print(arr.itemsize) # lenght of each element of array in bytes
print(arr.dtype)  # data type of an array

(2, 4)
2
8
int64


In [50]:
arr =np.array([[11, 22, 33, 44], [55, 66, 77, 88]], dtype=np.int8)
arr.dtype

dtype('int8')

In [51]:
arr =np.array([[11, 22, 33, 44], [55, 66, 77, 88]], dtype=np.int16)
arr.dtype

dtype('int16')

In [56]:
# numpy.empty
arr = np.empty((3,4), dtype=int)
arr

array([[                  0,                   0,                   0,
                          0],
       [                  0,                   0,                   0,
                          0],
       [                  0,                  90, 5764607523034234880,
        2305851774673921813]])

## Reading an writing:Text file to an Array and vice versa

In [58]:
# reading the file and storing the data in an array
arr = np.loadtxt(r'/Users/gyanendrakumar/PycharmProjects/education_DS/Module_5_PythonOnly/filex.txt',
                dtype=int)
arr

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  3,  4,  5,  5,  1,  8],
       [ 6,  3,  4,  5,  5,  1,  8],
       [ 6,  3,  4,  5,  5,  1,  8],
       [ 4,  3,  4,  5,  5,  1, 10]])

In [60]:
# exporting an array to a file
np.savetxt('output_march9th.txt', arr, fmt='%d')

In [63]:
np.savetxt('output_march9th_comma.txt',
           arr,
           fmt='%d',
          delimiter='#',
          header="education Rocks",
          footer='Python rocks')

## Reading csv file: csv to an array.

In [65]:
arr = np.genfromtxt(r'/Users/gyanendrakumar/PycharmProjects/education_DS/Module_5_PythonOnly/sujata.csv',
             delimiter=',')
arr

array([[10., 20., 30., 40.],
       [10., 20., 30., 40.],
       [10., 20., 30., 40.],
       [10., 20., 30., 40.]])

In [68]:
# export array to CSV
np.savetxt('march_9th_out.csv',
           arr,
           delimiter='&',
          fmt='%d')

# pandas

## series

In [69]:
import pandas as pd

In [70]:
# creating a series
ser = pd.Series()
ser

Series([], dtype: float64)

In [71]:
type(ser)

pandas.core.series.Series

In [ ]:
# series is a class in Python

In [72]:
# using dict
d = {'a':100, 'b':200, 'c':400}
ser = pd.Series(d)
ser

a    100
b    200
c    400
dtype: int64

In [73]:
ser['a']

100

In [74]:
# series using list
ser = pd.Series([11, 12, 13, 14])
ser

0    11
1    12
2    13
3    14
dtype: int64

In [75]:
# slicing concept is same as seen in list
ser[1:5]

1    12
2    13
3    14
dtype: int64

In [76]:
ser[1:]

1    12
2    13
3    14
dtype: int64

# DataFrame

In [77]:
#1. creating using a list
a = [11, 22, 33, 44, 55]
df = pd.DataFrame(a)
df

0
0  11
1  22
2  33
3  44
4  55

In [78]:
#2. creating using a list of dict
d = [{'a':11, 'b':22}, {'a':11, 'b':22, 'c':33}]
df = pd.DataFrame(d)
df

a   b     c
0  11  22   NaN
1  11  22  33.0

In [ ]:
# NaN : Not a Number

In [79]:
# choose index of you own choice
d = [{'a':11, 'b':22}, {'a':11, 'b':22, 'c':33}]
df = pd.DataFrame(d, index=['first', 'second'])
df

a   b     c
first   11  22   NaN
second  11  22  33.0

In [85]:
# 3. using a dict with series
d = {'a':pd.Series([11, 22, 33], index=['i', 'j', 'k']),
    'b':pd.Series([44, 55, 66, 77], index=['i', 'j', 'k','l'])}
df = pd.DataFrame(d)
df

a   b
i  11.0  44
j  22.0  55
k  33.0  66
l   NaN  77

In [89]:
# 4. using a dict
d = {'a':[11, 22, 33, 44],
    'b':[10, 20, 30, 40]}
df = pd.DataFrame(d, index=[100, 200, 300, 400])
df

a   b
100  11  10
200  22  20
300  33  30
400  44  40

# Addition and deletion of columns

In [91]:
d = {'age':[30, 42, 53, 64],
    'experience':[10, 20, 30, 35]}
df = pd.DataFrame(d)
df

age  experience
0   30          10
1   42          20
2   53          30
3   64          35

In [92]:
# addition of a column 'salary'
df['salary'] = df['experience']*3
df

age  experience  salary
0   30          10      30
1   42          20      60
2   53          30      90
3   64          35     105

In [93]:
# access a column
df['salary']

0     30
1     60
2     90
3    105
Name: salary, dtype: int64

In [94]:
# delete a column using 'del' keyword
del df['salary']
df

age  experience
0   30          10
1   42          20
2   53          30
3   64          35

In [98]:
# delete a column using pop()
d = {'age':[30, 42, 53, 64],
    'experience':[10, 20, 30, 35]}
df = pd.DataFrame(d)
df.pop('age')  # returns the delete column

0    30
1    42
2    53
3    64
Name: age, dtype: int64

In [96]:
df

experience
0          10
1          20
2          30
3          35

## access a column

In [99]:
d = {'age':[30, 42, 53, 64],
    'experience':[10, 20, 30, 35]}
df = pd.DataFrame(d)
df

age  experience
0   30          10
1   42          20
2   53          30
3   64          35

In [100]:
# access df[<column_name>]
df['age']

0    30
1    42
2    53
3    64
Name: age, dtype: int64

## accessing a row from a DataFrame
- df.loc[index_name] location name
- df.iloc[position_from_the_top] . starting from 0, iloc means index location from the top

In [106]:
d = {'age':[30, 42, 53, 64],
    'experience':[10, 20, 30, 35]}
df = pd.DataFrame(d, index=['a', 'b', 'c', 'd'])
df

age  experience
a   30          10
b   42          20
c   53          30
d   64          35

In [109]:
df.loc['a']

age           30
experience    10
Name: a, dtype: int64

In [110]:
type(df.loc['a'])

pandas.core.series.Series

### iloc

In [111]:
df.iloc[0]

age           30
experience    10
Name: a, dtype: int64

In [112]:
df.iloc[2]

age           53
experience    30
Name: c, dtype: int64

In [113]:
# case 2: when user defined index is number
d = {'age':[30, 42, 53, 64],
    'experience':[10, 20, 30, 35]}
df = pd.DataFrame(d, index=[10, 20, 30, 40])
df

age  experience
10   30          10
20   42          20
30   53          30
40   64          35

In [114]:
df.loc[10]

age           30
experience    10
Name: 10, dtype: int64

In [115]:
df.iloc[0]

age           30
experience    10
Name: 10, dtype: int64

In [117]:
df.iloc[3]

age           64
experience    35
Name: 40, dtype: int64

In [118]:
# case 3: when user defined index is not there
d = {'age':[30, 42, 53, 64],
    'experience':[10, 20, 30, 35]}
df = pd.DataFrame(d)
df

age  experience
0   30          10
1   42          20
2   53          30
3   64          35

In [119]:
# in this case both loc and iloc would take same input
df.loc[0]

age           30
experience    10
Name: 0, dtype: int64

In [120]:
df.iloc[0]

age           30
experience    10
Name: 0, dtype: int64

In [121]:
# case 4: when user defined index is number
# in pandas row indexes can be duplicated
d = {'age':[30, 42, 53, 64],
    'experience':[10, 20, 30, 35]}
df = pd.DataFrame(d, index=[0, 0, 1, 2])
df

age  experience
0   30          10
0   42          20
1   53          30
2   64          35

In [122]:
df.loc[0]

age  experience
0   30          10
0   42          20

In [123]:
df.iloc[0]

age           30
experience    10
Name: 0, dtype: int64

## Row addition

In [133]:
data = {'one':pd.Series([1,2,3], index=['a', 'b', 'c']),
       'two':pd.Series([10,20,30,40], index=['a', 'b', 'c', 'd']),
       'three':pd.Series([10,20,30], index=['a', 'b', 'c'])}
df1 = pd.DataFrame(data)
print(df1)
print("#"*10)
df2 = pd.DataFrame([[11,12], [13,14]], columns=['two', 'three'])
print(df2)
print("#"*10)
new_df = df1.append(df2)
print(new_df)

   one  two  three
a  1.0   10   10.0
b  2.0   20   20.0
c  3.0   30   30.0
d  NaN   40    NaN
##########
   two  three
0   11     12
1   13     14
##########
   one  three  two
a  1.0   10.0   10
b  2.0   20.0   20
c  3.0   30.0   30
d  NaN    NaN   40
0  NaN   12.0   11
1  NaN   14.0   13


### delete a row

In [138]:
data = {'one':pd.Series([1,2,3], index=['a', 'b', 'c']),
       'two':pd.Series([10,20,30,40], index=['a', 'b', 'c', 'd']),
       'three':pd.Series([10,20,30], index=['a', 'b', 'c'])}
df1 = pd.DataFrame(data)
print(df1)
print("#########")
df1 = df1.drop('a')
print(df1)

   one  two  three
a  1.0   10   10.0
b  2.0   20   20.0
c  3.0   30   30.0
d  NaN   40    NaN
#########
   one  two  three
b  2.0   20   20.0
c  3.0   30   30.0
d  NaN   40    NaN


## Importing and exporting the data from a file to DF

In [140]:
# reading csv
path = r'/Users/gyanendrakumar/PycharmProjects/education_DS/Module_5_PythonOnly/775_m5_datasets_v1.0/sample-salesv2.csv'
df = pd.read_csv(path)
df.head() # first five rows only

account_number                           name item_code category  quantity  \
0          296809                    Carroll PLC  QN-82852     Belt        13   
1           98022              Heidenreich-Bosco  MJ-21460    Shoes        19   
2          563905  Kerluke, Reilly and Bechtelar  AS-93055    Shirt        12   
3           93356                  Waters-Walker  AS-93055    Shirt         5   
4          659366                  Waelchi-Fahey  AS-93055    Shirt        18   

   unit price  net_price              date  
0       44.48     578.24  27-09-2014 07:13  
1       53.62    1018.78  29-07-2014 02:10  
2       24.16     289.92  01-03-2014 10:51  
3       82.68     413.40  17-11-2013 20:41  
4       99.64    1793.52  03-01-2014 08:14

In [141]:
type(df)

pandas.core.frame.DataFrame

In [142]:
df['category']

0       Belt
1      Shoes
2      Shirt
3      Shirt
4      Shirt
5      Shirt
6      Shoes
7      Shoes
8      Shoes
9      Shirt
10     Shirt
11      Belt
12     Shoes
13     Shirt
14     Shoes
15     Shoes
16     Shirt
17     Shirt
18      Belt
19     Shirt
20      Belt
21     Shoes
22     Shoes
23      Belt
24     Shirt
25      Belt
26     Shirt
27     Shoes
28     Shirt
29     Shirt
       ...  
970     Belt
971    Shoes
972    Shoes
973    Shirt
974    Shirt
975    Shoes
976    Shoes
977    Shoes
978    Shirt
979     Belt
980     Belt
981     Belt
982    Shirt
983    Shoes
984    Shirt
985    Shoes
986    Shirt
987     Belt
988    Shoes
989    Shoes
990    Shirt
991     Belt
992    Shirt
993    Shoes
994     Belt
995     Belt
996    Shoes
997    Shoes
998    Shoes
999    Shoes
Name: category, Length: 1000, dtype: object

In [146]:
# export the df to a csv file
df.to_csv('hello.csv', index=False)