# Module 5

## numpy

In [1]:
import numpy as np

In [2]:
# 1D array
arr = np.array([11, 12, 13, 14])
arr

array([11, 12, 13, 14])

In [3]:
# 2D array
data = [[11, 22], [33, 44]]
arr = np.array(data)
arr


array([[11, 22],
       [33, 44]])

In [4]:
# shape of an array (rows, cols)
arr.shape

(2, 2)

In [5]:
# using arange(start, stop)
np.arange(2, 10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
# np.zeros(shape)
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [7]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
np.zeros((4,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [9]:
# linearly spaced array
# np.linspace(start, stop, no_of_values_between_start_and_stop)
np.linspace(0, 20, 5)

array([ 0.,  5., 10., 15., 20.])

In [10]:
np.linspace(0, 20, 6)

array([ 0.,  4.,  8., 12., 16., 20.])

In [11]:
np.linspace(0, 20, 7)

array([ 0.        ,  3.33333333,  6.66666667, 10.        , 13.33333333,
       16.66666667, 20.        ])

In [15]:
## Restructuring of an array i.e shape manipulation
# NOTE: valid shape will have same number of elements

arr = np.zeros(16)
print(arr)

arr_2d = arr.reshape((4,4))
arr_2d

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
arr = np.zeros(8)
print(arr)
arr_3d = arr.reshape((2,2,2))
arr_3d

[0. 0. 0. 0. 0. 0. 0. 0.]


array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [20]:
## Flattening the array
arr_2d = np.array([[22,33], [44,55]])
print(arr_2d)
print("Flatenning the array")
arr_1d = arr_2d.ravel()
print(arr_1d)

[[22 33]
 [44 55]]
Flatenning the array
[22 33 44 55]


In [22]:
# converting 1D array to a list object
list((arr_1d))

[22, 33, 44, 55]

In [25]:
## Indexing
# arr[index]

arr = np.arange(3,20)
arr

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [24]:
arr[0]  # first value

3

In [27]:
arr[-1]  # last value

19

In [28]:
arr[2]  # third value

5

In [35]:
## 1D array accessing multiple values together
# array[list_of_indexes]
arr = np.array([11, 22, 33, 44, 55, 66, 77, 88])
arr[[0,2,3,5]]

array([11, 33, 44, 66])

In [29]:
# accessing value using Index in 2D array
arr = np.array([[11,22,33,44],[55,66,77,88], [99,12,13,14], [15,16,17,18]])
arr

array([[11, 22, 33, 44],
       [55, 66, 77, 88],
       [99, 12, 13, 14],
       [15, 16, 17, 18]])

In [32]:
# syantx: arr[row_index, col_index]
arr[0,2]  

33

In [38]:
## slicing for 1D array is same as list , tuples and strings

arr = np.array([11, 22, 33, 44, 55, 66, 77, 88])
arr[1:3]


array([22, 33])

In [39]:
## slicing for 2D array
# syntax: arr[row_slice, column_slice]
arr_2d = np.array([[11,22,33,44],[55,66,77,88], [99,12,13,14], [15,16,17,18]])
arr_2d

array([[11, 22, 33, 44],
       [55, 66, 77, 88],
       [99, 12, 13, 14],
       [15, 16, 17, 18]])

In [40]:
arr_2d[0:2, 0:2]

array([[11, 22],
       [55, 66]])

In [41]:
arr_2d[0:3, 0:2]

array([[11, 22],
       [55, 66],
       [99, 12]])

## Numpy array attributes

In [44]:
arr_2d

array([[11, 22, 33, 44],
       [55, 66, 77, 88],
       [99, 12, 13, 14],
       [15, 16, 17, 18]])

In [46]:
# shape returns no of rows and no of columns
arr_2d.shape

(4, 4)

In [48]:
# dimension of an array ex: 1D or 2D or 3D
arr_2d.ndim  # 2 means the array is 2D array

2

In [49]:
# length of each element of an array
arr_2d.itemsize  # 8 bytes

8

In [56]:
# select the itemsize using np.int8, np.int16, np.int32, np.int64
arr = np.array([[11,22],[33,44]], dtype=np.int16)
arr

array([[11, 22],
       [33, 44]], dtype=int16)

In [57]:
arr.itemsize

2

In [58]:
2**16

65536

In [61]:
arr = np.array([[11,22],[33,44]])
print(arr.dtype)
print(arr.itemsize)  # default integer is 8bytes

int64
8


In [62]:
# creating an uninitialized array or junk element array
# np.empty(shape)
np.empty((3,2))

array([[ 3.33333333,  6.66666667],
       [10.        , 13.33333333],
       [16.66666667, 20.        ]])

In [65]:
np.empty((3,5))

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 1.49457241e-154, 1.72723371e-077,
        1.72723371e-077, 2.35383005e-314]])

## reading and writing from a text file

In [66]:
arr_2d = np.loadtxt('filex.txt')
arr_2d

array([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.],
       [ 8.,  3.,  4.,  5.,  5.,  1.,  8.],
       [ 6.,  3.,  4.,  5.,  5.,  1.,  8.],
       [ 6.,  3.,  4.,  5.,  5.,  1.,  8.],
       [ 4.,  3.,  4.,  5.,  5.,  1., 10.]])

In [67]:
arr_2d.dtype # by default it is a float value

dtype('float64')

In [69]:
arr_2d = np.loadtxt('filex.txt', dtype=int)
arr_2d

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  3,  4,  5,  5,  1,  8],
       [ 6,  3,  4,  5,  5,  1,  8],
       [ 6,  3,  4,  5,  5,  1,  8],
       [ 4,  3,  4,  5,  5,  1, 10],
       [ 4,  3,  4,  5,  5,  1, 10],
       [ 4,  3,  4,  5,  5,  1, 10],
       [ 4,  3,  4,  5,  5,  1, 10],
       [ 4,  3,  4,  5,  5,  1, 10],
       [ 4,  3,  4,  5,  5,  1, 10],
       [ 4,  3,  4,  5,  5,  1, 10],
       [ 4,  3,  4,  5,  5,  1, 10],
       [ 4,  3,  4,  5,  5,  1, 10],
       [ 4,  3,  4,  5,  5,  1, 10]])

In [70]:
arr_2d[0:5] # first five rows

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  3,  4,  5,  5,  1,  8],
       [ 6,  3,  4,  5,  5,  1,  8],
       [ 6,  3,  4,  5,  5,  1,  8],
       [ 4,  3,  4,  5,  5,  1, 10]])

In [73]:
arr_2d[0:5,0:5] # first five rows and first 5 columns

array([[1, 2, 3, 4, 5],
       [8, 3, 4, 5, 5],
       [6, 3, 4, 5, 5],
       [6, 3, 4, 5, 5],
       [4, 3, 4, 5, 5]])

### export an array to a file

In [80]:
arr = arr_2d[0:5,0:5]
arr.dtype
np.savetxt('abidali.txt', arr,fmt='%d', header='hello')

In [77]:
help(np.savetxt)

Help on function savetxt in module numpy:

savetxt(fname, X, fmt='%.18e', delimiter=' ', newline='\n', header='', footer='', comments='# ', encoding=None)
    Save an array to a text file.
    
    Parameters
    ----------
    fname : filename or file handle
        If the filename ends in ``.gz``, the file is automatically saved in
        compressed gzip format.  `loadtxt` understands gzipped files
        transparently.
    X : 1D or 2D array_like
        Data to be saved to a text file.
    fmt : str or sequence of strs, optional
        A single format (%10.5f), a sequence of formats, or a
        multi-format string, e.g. 'Iteration %d -- %10.5f', in which
        case `delimiter` is ignored. For complex `X`, the legal options
        for `fmt` are:
    
        * a single specifier, `fmt='%.4e'`, resulting in numbers formatted
          like `' (%s+%sj)' % (fmt, fmt)`
        * a full string specifying every real and imaginary part, e.g.
          `' %.4e %+.4ej %.4e %+.4ej %.4

In [81]:
arr

array([[1, 2, 3, 4, 5],
       [8, 3, 4, 5, 5],
       [6, 3, 4, 5, 5],
       [6, 3, 4, 5, 5],
       [4, 3, 4, 5, 5]])

In [82]:
# maximum value of an array
arr.max()

8

In [83]:
# minimum value of an array
arr.min()

1

In [84]:
arr.std()  # standard deviation

1.4005713120009278

In [86]:
arr.mean()  # average

4.28

In [91]:
arr[0].max()  # maximum value for first row

5

In [93]:
# using "delimiter"
arr = arr_2d[0:5,0:5]
arr.dtype
np.savetxt('abidali_dollar.txt', arr,fmt='%d', delimiter='$')

### reading csv file or any file to an array
- make sure to provide a delimiter

In [95]:
arr = np.genfromtxt('sujata.csv', delimiter=',')
arr

array([[10., 20., 30., 40.],
       [10., 20., 30., 40.],
       [10., 20., 30., 40.],
       [10., 20., 30., 40.]])

In [96]:
help(np.genfromtxt)

Help on function genfromtxt in module numpy:

genfromtxt(fname, dtype=<class 'float'>, comments='#', delimiter=None, skip_header=0, skip_footer=0, converters=None, missing_values=None, filling_values=None, usecols=None, names=None, excludelist=None, deletechars=None, replace_space='_', autostrip=False, case_sensitive=True, defaultfmt='f%i', unpack=None, usemask=False, loose=True, invalid_raise=True, max_rows=None, encoding='bytes')
    Load data from a text file, with missing values handled as specified.
    
    Each line past the first `skip_header` lines is split at the `delimiter`
    character, and characters following the `comments` character are discarded.
    
    Parameters
    ----------
    fname : file, str, pathlib.Path, list of str, generator
        File, filename, list, or generator to read.  If the filename
        extension is `.gz` or `.bz2`, the file is first decompressed. Note
        that generators must return byte strings in Python 3k.  The strings
        in a 

# pandas library

### Series

In [98]:
# create
import pandas as pd
ser = pd.Series()
ser

Series([], dtype: float64)

In [99]:
# using a sequence(list, tuple, string, array)
ser = pd.Series([11, 22, 33, 44])
ser

0    11
1    22
2    33
3    44
dtype: int64

In [100]:
# using an array
arr = np.array([100, 200, 300, 400])
ser = pd.Series(arr)
ser

0    100
1    200
2    300
3    400
dtype: int64

In [101]:
# choosing dtype
arr = np.array([100, 200, 300, 400])
ser = pd.Series(arr, dtype=float)
ser

0    100.0
1    200.0
2    300.0
3    400.0
dtype: float64

In [102]:
# using dictionary
my_dict = {'a':100, 'b':200, 'c':300, 'd':400}
ser = pd.Series(my_dict)
ser

a    100
b    200
c    300
d    400
dtype: int64

In [103]:
# indexing: Syntax: series[index]
arr = np.array([100, 200, 300, 400])
ser = pd.Series(arr, dtype=float)
ser

0    100.0
1    200.0
2    300.0
3    400.0
dtype: float64

In [104]:
# ser[index]
ser[0]

100.0

In [106]:
ser[3]

400.0

In [108]:
#example 2: for indexing
my_dict = {'a':100, 'b':200, 'c':300, 'd':400}
ser = pd.Series(my_dict)
ser

a    100
b    200
c    300
d    400
dtype: int64

In [109]:
ser['a']

100

In [110]:
ser['b']

200

## DataFrame

In [112]:
# list of dicts
data = [{'a':1, 'b':2}, {'a':10, 'b':20, 'c':30}]
df = pd.DataFrame(data)
df

a   b     c
0   1   2   NaN
1  10  20  30.0

In [113]:
# NaN : not a number is stored in the place of missing values

In [114]:
# providing names for rows/indexs 
df = pd.DataFrame(data, index=['first', 'second'])
df

a   b     c
first    1   2   NaN
second  10  20  30.0

In [115]:
# 3. using a dict with series
d = {'a':pd.Series([11, 22, 33], index=['i', 'j', 'k']),
    'b':pd.Series([44, 55, 66, 77], index=['i', 'j', 'k','l'])}
df = pd.DataFrame(d)
df

a   b
i  11.0  44
j  22.0  55
k  33.0  66
l   NaN  77

In [120]:
# access a column from a dataframe
# NOTE: each column is a Series

In [117]:
data = [{'a':1, 'b':2}, {'a':10, 'b':20, 'c':30}]
df = pd.DataFrame(data)
df

a   b     c
0   1   2   NaN
1  10  20  30.0

In [119]:
# access
df['b']

0     2
1    20
Name: b, dtype: int64

In [121]:
type(df['b'])

pandas.core.series.Series

In [122]:
# dataframe is a combination of multiple series

In [123]:
# adding a column to a dataframe
df

a   b     c
0   1   2   NaN
1  10  20  30.0

In [124]:
df['new_col'] = [100, 200]
df

a   b     c  new_col
0   1   2   NaN      100
1  10  20  30.0      200

In [125]:
# delete a column
del(df['a'])
df

b     c  new_col
0   2   NaN      100
1  20  30.0      200

In [126]:
df

b     c  new_col
0   2   NaN      100
1  20  30.0      200

In [127]:
df.pop('new_col')
df

b     c
0   2   NaN
1  20  30.0

## accessing a row from a DataFrame
- **df.loc[index_name]** location name
- **df.iloc[position_from_the_top]** . starting from 0, iloc means index location from the top

In [147]:
d = {'age':[30, 42, 53, 64],
    'experience':[10, 20, 30, 35]}
df = pd.DataFrame(d, index=['a', 'b', 'c', 'd'])
df

age  experience
a   30          10
b   42          20
c   53          30
d   64          35

In [148]:
# using loc[index_name]
df.loc['c']  # series

age           53
experience    30
Name: c, dtype: int64

In [149]:
df.loc['c']

age           53
experience    30
Name: c, dtype: int64

In [150]:
# using iloc
df.iloc[2]  # same as df.loc['c']

age           53
experience    30
Name: c, dtype: int64

In [152]:
#  when user defined index is number
# in pandas row indexes can be duplicated
d = {'age':[30, 42, 53, 64],
    'experience':[10, 20, 30, 35]}
df = pd.DataFrame(d, index=[0, 0, 1, 2])
df

age  experience
0   30          10
0   42          20
1   53          30
2   64          35

In [156]:
df.loc[0]

age  experience
0   30          10
0   42          20

### addition and deletion of rows in a DF

In [159]:
data = {'one':pd.Series([1,2,3], index=['a', 'b', 'c']),
       'two':pd.Series([10,20,30,40], index=['a', 'b', 'c', 'd']),
       'three':pd.Series([10,20,30], index=['a', 'b', 'c'])}
df1 = pd.DataFrame(data)
print(df1)
print("#"*10)
df2 = pd.DataFrame([[11,12], [13,14]], columns=['two', 'three'])
print(df2)
print("#"*10)
new_df = df1.append(df2, sort=False)
print(new_df)

   one  two  three
a  1.0   10   10.0
b  2.0   20   20.0
c  3.0   30   30.0
d  NaN   40    NaN
##########
   two  three
0   11     12
1   13     14
##########
   one  two  three
a  1.0   10   10.0
b  2.0   20   20.0
c  3.0   30   30.0
d  NaN   40    NaN
0  NaN   11   12.0
1  NaN   13   14.0


In [161]:
# deleting a row

data = {'one':pd.Series([1,2,3], index=['a', 'b', 'c']),
       'two':pd.Series([10,20,30,40], index=['a', 'b', 'c', 'd']),
       'three':pd.Series([10,20,30], index=['a', 'b', 'c'])}
df1 = pd.DataFrame(data)
print(df1)
print("#########")
df1 = df1.drop('a')
print(df1)

   one  two  three
a  1.0   10   10.0
b  2.0   20   20.0
c  3.0   30   30.0
d  NaN   40    NaN
#########
   one  two  three
b  2.0   20   20.0
c  3.0   30   30.0
d  NaN   40    NaN


## Loading a csv file into a DataFrame

In [162]:
df = pd.read_csv('AllCountries.csv')
print(type(df))


<class 'pandas.core.frame.DataFrame'>


In [163]:
df

Country  LandArea  Population      GDP  Rural  Internet  \
0                 Afghanistan   652.860      30.552    665.0   74.1       5.9   
1                     Albania    27.400       2.897   4460.0   44.6      60.1   
2                     Algeria  2381.740      39.208   5361.0   30.5      16.5   
3              American Samoa     0.200       0.055      NaN   12.7       NaN   
4                     Andorra     0.470       0.079      NaN   13.8      94.0   
5                      Angola  1246.700      21.472   5783.0   57.5      19.1   
6         Antigua and Barbuda     0.440       0.090  13342.0   75.4      63.4   
7                   Argentina  2736.690      41.446  14715.0    8.5      59.9   
8                     Armenia    28.470       2.977   3505.0   37.0      46.3   
9                       Aruba     0.180       0.103      NaN   57.9      78.9   
10                  Australia  7682.300      23.129  67463.0   10.8      83.0   
11                    Austria    82.409       8.480  50511.0   34.1      80.6   
12                 Azerbaijan    82.658       9.417   7812.0   45.9      58.7   
13               Bahamas, The    10.010       0.377  22312.0   17.3      72.0   
14                    Bahrain     0.760       1.332  24689.0   11.3      90.0   
15                 Bangladesh   130.170     156.595    958.0   67.2       6.5   
16                   Barbados     0.430       0.285      NaN   68.3      75.0   
17                    Belarus   202.910       9.466   7575.0   24.1      54.2   
18                    Belgium    30.280      11.183  46930.0    2.2      82.2   
19                     Belize    22.810       0.332   4894.0   55.7      31.7   
20                      Benin   112.760      10.323    805.0   56.9       4.9   
21                    Bermuda     0.050       0.065      NaN    0.0      95.3   
22                     Bhutan    38.117       0.754   2363.0   62.9      29.9   
23                    Bolivia  1083.300      10.671   2868.0   32.3      39.5   
24     Bosnia and Herzegovina    51.000       3.829   4662.0   60.5      67.9   
25                   Botswana   566.730       2.021   7315.0   43.1      15.0   
26                     Brazil  8358.140     200.362  11208.0   14.8      51.6   
27          Brunei Darussalam     5.270       0.418  38563.0   23.4      64.5   
28                   Bulgaria   108.560       7.265   7499.0   26.7      53.1   
29               Burkina Faso   273.600      16.935    761.0   71.8       4.4   
..                        ...       ...         ...      ...    ...       ...   
185                    Sweden   407.340       9.600  60381.0   14.5      94.8   
186               Switzerland    39.516       8.088  84748.0   26.2      86.7   
187      Syrian Arab Republic   183.630      22.846      NaN   43.1      26.2   
188                Tajikistan   139.960       8.208   1037.0   73.4      16.0   
189                  Tanzania   885.800      49.253    913.0   69.8       4.4   
190                  Thailand   510.890      67.011   5779.0   52.1      28.9   
191               Timor-Leste    14.870       1.180      NaN   68.5       1.1   
192                      Togo    54.390       6.817    636.0   61.0       4.5   
193                     Tonga     0.720       0.105   4427.0   76.4      35.0   
194       Trinidad and Tobago     5.130       1.341  18373.0   91.3      63.8   
195                   Tunisia   155.360      10.887   4317.0   33.5      43.8   
196                    Turkey   769.630      74.933  10972.0   27.6      46.3   
197              Turkmenistan   469.930       5.240   7987.0   50.7       9.6   
198  Turks and Caicos Islands     0.950       0.033      NaN    8.5       NaN   
199                    Tuvalu     0.030       0.010   3880.0   42.2      37.0   
200                    Uganda   199.810      37.579    657.0   84.6      16.2   
201                   Ukraine   579.320      45.490   3900.0   30.7      41.8   
202      United Arab Emirates    83.600       9.346  

In [166]:
#exporting a dataframe from a file
df.to_csv('output_batch29th.csv', index=False)

In [165]:
help(df.to_csv)

Help on method to_csv in module pandas.core.generic:

to_csv(path_or_buf=None, sep=',', na_rep='', float_format=None, columns=None, header=True, index=True, index_label=None, mode='w', encoding=None, compression='infer', quoting=None, quotechar='"', line_terminator=None, chunksize=None, tupleize_cols=None, date_format=None, doublequote=True, escapechar=None, decimal='.') method of pandas.core.frame.DataFrame instance
    Write object to a comma-separated values (csv) file.
    
    .. versionchanged:: 0.24.0
        The order of arguments for Series was changed.
    
    Parameters
    ----------
    path_or_buf : str or file handle, default None
        File path or object, if None is provided the result is returned as
        a string.  If a file object is passed it should be opened with
        `newline=''`, disabling universal newlines.
    
        .. versionchanged:: 0.24.0
    
           Was previously named "path" for Series.
    
    sep : str, default ','
        String of l

In [168]:
# reading an excel file
#pd.read_excel()

# exporting to an excel file
#df.to_excel(file.xls)

In [170]:
df.head()

Country  LandArea  Population     GDP  Rural  Internet  BirthRate  \
0     Afghanistan    652.86      30.552   665.0   74.1       5.9       34.1   
1         Albania     27.40       2.897  4460.0   44.6      60.1       12.9   
2         Algeria   2381.74      39.208  5361.0   30.5      16.5       24.3   
3  American Samoa      0.20       0.055     NaN   12.7       NaN        NaN   
4         Andorra      0.47       0.079     NaN   13.8      94.0        NaN   

   DeathRate  ElderlyPop  LifeExpectancy  FemaleLabor  Unemployment  
0        7.8         2.3            60.9         16.2           NaN  
1        6.9        10.7            77.5         51.7          13.4  
2        5.9         4.6            71.0         16.2          11.0  
3        NaN         NaN             NaN          NaN           NaN  
4        NaN         NaN             NaN          NaN           NaN

In [184]:
data = {'Email':['hello@gmail.com', 'bye@yahoo.com'],'Name':['RAvi', 'Shyam']}
df = pd.DataFrame(data)
df

Email   Name
0  hello@gmail.com   RAvi
1    bye@yahoo.com  Shyam

In [185]:
import re
def func(param):
    if isinstance(param, list):
        for elem in param:
            outout = re.search()
    return 
        
        
df['Domain_Name'] = df['Email'].apply(func)
df

Email   Name Domain_Name
0  hello@gmail.com   RAvi   gmail.com
1    bye@yahoo.com  Shyam   yahoo.com